Star disc example npars issue
Star disc example won't run because there's an AttributeError: 'list' object has no attribute 'npars'. This only happens when using the IRS spectrum. I am creating the data sets using the Spectrum class in the default manner (CASSIS spectrum). Something, somewhere is broken.